/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.amberdata.api;

import io.amberdata.model.Address;
import io.amberdata.model.Address1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-08T19:03:46.332-05:00")

@Api(value = "addresses", description = "the addresses API")
public interface AddressesApi {

    @ApiOperation(value = "", nickname = "addressesIdDelete", notes = "Delete a single address", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Addresses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted an address"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/addresses/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> addressesIdDelete(@ApiParam(value = "The address hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "addressesIdGet", notes = "Fetch an address", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Addresses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns a single address"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/addresses/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Void> addressesIdGet(@ApiParam(value = "The address hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "addressesIdPatch", notes = "Update a single address", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Addresses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated an address"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/addresses/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> addressesIdPatch(@ApiParam(value = "The address hash",required=true) @PathVariable("id") String id,@ApiParam(value = "Specify an entire address object"  )  @Valid @RequestBody Address1 address);


    @ApiOperation(value = "", nickname = "addressesPost", notes = "Add a new address", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Addresses", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns success") })
    @RequestMapping(value = "/addresses",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addressesPost(@ApiParam(value = "Specify an entire address object"  )  @Valid @RequestBody Address address);

}
