/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.amberdata.api;

import io.amberdata.model.Block;
import io.amberdata.model.Block1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-08T19:03:46.332-05:00")

@Api(value = "blocks", description = "the blocks API")
public interface BlocksApi {

    @ApiOperation(value = "", nickname = "blocksIdDelete", notes = "Delete a single block", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Blocks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted a block"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/blocks/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> blocksIdDelete(@ApiParam(value = "The block number",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "blocksIdGet", notes = "Fetch a block", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Blocks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns a single block"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/blocks/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Void> blocksIdGet(@ApiParam(value = "The block number or hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "blocksIdGteDelete", notes = "Delete all blocks above ID", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Blocks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted blocks"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/blocks/{id}/gte",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> blocksIdGteDelete(@ApiParam(value = "The block number",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "blocksIdPatch", notes = "Update a single block", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Blocks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated a block"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/blocks/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> blocksIdPatch(@ApiParam(value = "The block number or hash",required=true) @PathVariable("id") String id,@ApiParam(value = "Specify an entire block object"  )  @Valid @RequestBody Block1 block);


    @ApiOperation(value = "", nickname = "blocksPost", notes = "Add a new block or blocks", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Blocks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns success") })
    @RequestMapping(value = "/blocks",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> blocksPost(@ApiParam(value = "Specify an entire block object or an array of block objects"  )  @Valid @RequestBody Block block);

}
