/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.amberdata.api;

import io.amberdata.model.FunctionCall;
import io.amberdata.model.FunctionCall1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-08T19:03:46.332-05:00")

@Api(value = "functions", description = "the functions API")
public interface FunctionsApi {

    @ApiOperation(value = "", nickname = "functionsIdDelete", notes = "Delete a single function call", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Function Calls", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted a function call"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/functions/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> functionsIdDelete(@ApiParam(value = "The function call number",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "functionsIdGet", notes = "Fetch a function call", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Function Calls", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns a single function call"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/functions/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Void> functionsIdGet(@ApiParam(value = "The function call number or hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "functionsIdPatch", notes = "Update a single function call", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Function Calls", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated a function call"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/functions/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> functionsIdPatch(@ApiParam(value = "The function call number or hash",required=true) @PathVariable("id") String id,@ApiParam(value = "Specify an entire block object"  )  @Valid @RequestBody FunctionCall1 block);


    @ApiOperation(value = "", nickname = "functionsPost", notes = "Add a new function call or function calls", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Function Calls", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns success") })
    @RequestMapping(value = "/functions",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> functionsPost(@ApiParam(value = "Specify an entire function call object or an array of function call objects"  )  @Valid @RequestBody FunctionCall functionCall);

}
