/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.amberdata.api;

import io.amberdata.model.Trade;
import io.amberdata.model.Trade1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-08T19:03:46.332-05:00")

@Api(value = "trades", description = "the trades API")
public interface TradesApi {

    @ApiOperation(value = "", nickname = "tradesIdDelete", notes = "Delete a single trade", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Trades", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Deleted a trade"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/trades/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> tradesIdDelete(@ApiParam(value = "The trade id",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "tradesIdGet", notes = "Fetch a trade", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Trades", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns a single trade"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/trades/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Void> tradesIdGet(@ApiParam(value = "The trade id",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "tradesIdPatch", notes = "Update a single trade", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Trades", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Updated a trade"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/trades/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> tradesIdPatch(@ApiParam(value = "The trade id",required=true) @PathVariable("id") String id,@ApiParam(value = "Specify an entire trade object"  )  @Valid @RequestBody Trade1 trade);


    @ApiOperation(value = "", nickname = "tradesPost", notes = "Add a new trade", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Trades", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns success") })
    @RequestMapping(value = "/trades",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> tradesPost(@ApiParam(value = "Specify an entire trade object"  )  @Valid @RequestBody Trade trade);

}
