/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.amberdata.api;

import io.amberdata.model.Uncle;
import io.amberdata.model.Uncle1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-08T19:03:46.332-05:00")

@Api(value = "uncles", description = "the uncles API")
public interface UnclesApi {

    @ApiOperation(value = "", nickname = "unclesIdDelete", notes = "Delete a single uncle", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Uncles", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Uncle deleted"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/uncles/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> unclesIdDelete(@ApiParam(value = "Uncle hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "unclesIdGet", notes = "Fetch a single unclen", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Uncles", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Uncle returned"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/uncles/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Void> unclesIdGet(@ApiParam(value = "Uncle hash",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "unclesIdPatch", notes = "Update a single uncle", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Uncles", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Uncle updated"),
        @ApiResponse(code = 401, message = "Unauthorized") })
    @RequestMapping(value = "/uncles/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> unclesIdPatch(@ApiParam(value = "Uncle hash",required=true) @PathVariable("id") String id,@ApiParam(value = "example" ,required=true )  @Valid @RequestBody Uncle1 uncle);


    @ApiOperation(value = "", nickname = "unclesPost", notes = "Add a new uncle or uncles", authorizations = {
        @Authorization(value = "AmberdataApiKey"),
        @Authorization(value = "AmberdataBlockchainId")
    }, tags={ "Uncles", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Uncle created") })
    @RequestMapping(value = "/uncles",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> unclesPost(@ApiParam(value = "example" ,required=true )  @Valid @RequestBody Uncle uncle);

}
